## YAML Template.
server:
    port: 9082
    servlet:
      context-path: /v1.0/
spring:
    application:
        name: domace-ms-pedidos-api
        version: 0.1
    datasource:
        url: jdbc:mysql://localhost:3306/domace
        username: root
        password:
        driver-class-name: com.mysql.jdbc.Driver
    jpa:
        database-platform: org.hibernate.dialect.MySQL5InnoDBDialect

log:
  level: TRACE
  console: true


